version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: subject_exam
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    # volumes:
    #   - db_data:/var/lib/mysql

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=subject_exam
      - DB_USER=root
      - DB_PASS=rootpass
    depends_on:
      - db

volumes:
  db_data:
